### ISSUE TITLE
Feature request: CORS support

### ISSUE THREAD

**Issue by typester** [davidesantangelo/feedi#6]
Hi,

Thanks for providing awesome API!
Anyway, I tried to use this API from my PWA style app, but it doesn't seem to support CORS right now.

Do you have any plan to support CORS?
I'm happy if you do so.

Thanks

**Comment by davidesantangelo** [comment]
Ehi typesetter thanks :). Feedi already support CORS. Can you provide more informations of your requests. Thanks.

**Comment by typester** [comment]
Oh, I missed that.

When I tried, I used curl as a testing client and didn't attach any Origin header.
Now I tried again with the header, it worked!

Please forget this issue.
And thank you for taking your time.
